### PR TITLE
2012 Nebraska general election by county with precincts

### PR DESCRIPTION
**Pull request by sdunbarne**
As mentioned last week, I have transformed the 2012 Nebraska general election county spreadsheets to the csv format by county with precinct level items.  Also included is a comprehensive statewide .csv file.  Some meta-data, documentation, notes, information, etc. is in 2012-nebraska-general.md in markdown format.  Also included is the R script used to transform the spreadsheets and the short bash script that combined all into the statewide file.

### CODE REVIEW

**Comment by dwillis** [comment]
Thanks, @sdunbarne!

**Comment by sdunbarne** [comment]
Now that Nebraska Generals for 2012 and 2014 are taken care of, I'm ready
to work on more data at your direction depending on your needs and
priorities.

I can either work locally pushing backwards in time on Nebraska to 2010,
etc,
OR
I can work on some other state that has higher priority.

Now that I have some experience, converting Excel files is preferred, but
any data conversion is fine.

-- Steve Dunbar

**Comment by dwillis** [comment]
If you'd like to keep working on Nebraska elections, it would be very useful to use to have those going back further. If not, [North Dakota](https://github.com/openelections/openelections-data-nd) also has excel files [going back to 2010](https://vip.sos.nd.gov/PortalListDetails.aspx?ptlhPKID=62&ptlPKID=4).

**Comment by sdunbarne** [comment]
Good, I'd like to continue to work on the Nebraska elections.  Where/how
did you obtain the 2014 and 2012 Nebraska general election results in
excel?  Knowing that I will try to obtain 2010, and before.
If that meets a roadblock, I'll turn my attention to North Dakota. until
the block gets cleared.

Steve Dunbar

**Comment by dwillis** [comment]
For 2010 Nebraska data, I wonder if it's worth asking the Secretary of State whether it has the precinct-level results? If you don't want to do that, we can make that request. I suspect in the meantime North Dakota might be more productive.

**Comment by sdunbarne** [comment]
I will try to follow up with the Secretary of State for 2010 (and before)
Nebraska elections.  That will probably take some time, so in the meantime,
I will begin working on North Dakota.  Updates when I have
results/progress.  -- Steve Dunbar

**Pull request merged**
